"""
flow_tools.py — auto-generated by the GUI's Flows tab. Each function
below corresponds to one saved node-graph flow.

DO NOT hand-edit the body of a generated function — re-saving that flow
from the GUI overwrites everything between its START/END markers.
"""

from gui.dispatch import _dispatch_midum_tool
import main as _midum


def _call_mcp_tool_step(server, tool_name, args):
    return _midum.call_mcp_tool(server, tool_name, args)


# === FLOW: Test1 ===
def Test1():
    """
    Auto-generated from the Flows tab's node graph. Edit the graph in
    the GUI and click Save to regenerate this function — manual edits
    made directly to this function body will be OVERWRITTEN the next
    time this flow is saved.
    """
    _flow_results = []
    # --- Start ---
    # --- Tool: execute_terminal_command ---
    _args = {'command': 'New-Item -Path "D:\\MidumTestFlow" -ItemType Directory'}
    _step = _dispatch_midum_tool('execute_terminal_command', _args)
    _flow_results.append(_step)
    # --- End ---
    return _flow_results[-1] if _flow_results else None
# === END FLOW: Test1 ===

